name: gh-pages

on:
  push:
    branches: [ master ]
    paths: [ '**.java' ]

jobs:
  api-website:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15

    - name: Build docs with Maven
      run: mvn javadoc:javadoc --no-transfer-progress

    - name: Copy to Documentation Website Location
      run: |
        rm -rf docs
        cp -rf target/site/apidocs/. docs
        rm -rf target
    - name: Tidy up the javadocs
      id: tidy
      uses: cicirello/javadoc-cleanup@v1.2.0
      with:
        path-to-root: docs
        base-url-path: https://fh-erfurt.github.io/Scooter-MS/index.html
    
    - name: Log javadoc-cleanup output
      run: |
        echo "modified-count = ${{ steps.tidy.outputs.modified-count }}"

      # Publishes created docs folder to gh-pages branch
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
